// =========================================================================
// ENUNCIADO: 
// Faça um programa que leia o nome de uma pessoa e mostre uma mensagem de boas
vindas para ela.
// =========================================================================

algoritmo "apresentacao"
var
   nome:caractere
inicio
   escreva("Qual o seu nome? ")
   leia(nome)
   escreva("Seja bem vindo ao mundo da programação ", nome)
fimalgoritmo
