algoritmo "Exercicio3"
// Função : Mostrar Funcionário e Salário
// Autor : Allan Sanches
// Data : 27/01/2026
// Seção de Declarações 
var
nome, salario:caractere
inicio
      escreva("Qual o nome do funcionário? ")
      leia(nome)
      escreva("Qual o salário do funcionário? ")
      leia(salario)
      escreval("Nome do Funcionário: ", nome)
      escreval("Salário: R$", salario)
      escreva("O funcionário ",nome, " tem o salário de R$", salario)
fimalgoritmo
